### ISSUE TITLE
docker issue login - NEXTAUTH_URL

### ISSUE THREAD

**Issue by shuther** [SecureAI-Tools/SecureAI-Tools#37]
I trie with 2 different NEXTAUTH_URL with no luck:

> #NEXTAUTH_URL="http://linuxmain.local:28669"
> NEXTAUTH_URL="http://192.168.0.120:28669"

Each time in the docker log I have the url:  http://localhost:28669 (not sure if expected)
The redirect (toward the correct NEXTAUTH_URL) is working after the login but I get an error 500

```
- ready started server on 0.0.0.0:28669, url: http://localhost:28669
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]
    at ServerResponse.setHeader (node:_http_outgoing:651:3)
    at _res.setHeader (/app/node_modules/next/dist/server/base-server.js:326:24)
    at NextAuthApiHandler (/app/node_modules/next-auth/next/index.js:43:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextAuth._args$ (/app/node_modules/next-auth/next/index.js:107:14) {
  code: 'ERR_INVALID_CHAR'
}
```

**Comment by JayNakrani** [comment]
What is the full URL (including search and hash param) that you're trying to access? What version of SecureAI Tools are you on?

This error happens when the URL has some invalid characters (most likely because some strings are not properly encoded in our code)

**Comment by charlyjna** [comment]
I am facing the same issue...
My NEXTAUTH_URL="http://10.12.12.18:28669/", I am able to connect the login page but then I have an error and the new URL is:

**Comment by JayNakrani** [comment]
@charlyjna In your case, it looks like you're being redirected to https by something (possibly a reverse proxy). Can you try specifying `NEXTAUTH_URL=https://10.12.12.18:28669` (https, no double quotes, and no trailing slash)?

**Comment by charlyjna** [comment]
@JayNakrani The URL is correctly rewrite now, but because it switches from http to https, I have now an invalid response: ERR_SSL_PROTOCOL_ERROR.
Should I enable SSL? Because http://10.12.12.18:28669 works but not https.

**Comment by JayNakrani** [comment]
@charlyjna Ah! If it works with http and you don't need https then no need to enable SSL.

> EDIT: I replace https by http to have 'NEXTAUTH_URL=http://10.12.12.18:28669/' only, and now I have another error `
http://10.12.12.18:28669/api/auth/error?error=error%3A%20Error%20validating%20datasource%20%60db%60%3A%20the%20URL%20must%20start%20with%20the%20protocol%20%60file%3A%60.%0A%20%20--%3E%20%20schema.prisma%3A10%0A%20%20%20%7C%20%0A%209%20%7C%20%20%20provider%20%3D%20%22sqlite%22%0A10%20%7C%20%20%20url%20%20%20%20%20%20%3D%20env(%22DATABASE_URL%22)%0A%20%20%20%7C%20%0A%0AValidation%20Error%20Count%3A%201`

This error means that `DATABASE_URL` is not properly configured: at or before `v0.0.1` it needs to start with `file:` like shown [here](https://github.com/SecureAI-Tools/SecureAI-Tools/blob/4fef4a61926239fbe6a7e19f5839d5eba88ba4fe/deployment/example.env#L41). What does it look like on your case?

**Comment by charlyjna** [comment]
Now I am facing the same issue than @shuther. Same error message.
I tried to get more details from `/app/nodes-modules/next-auth/next/index.js` and it seems that `handler.redirect` is the root cause in what is happening.

**Comment by JayNakrani** [comment]
> deployment-web-1

@shuther From the logs above, it looks like you may be running from main branch directly. Can you both confirm whether you are running from main branch directly @charlyjna @shuther?

The main branch is broken right now because we are doing a large refactor (splitting into turbo repo and moving from SQLite to Postgres). Can you please run it from the released version as [documented in the README here](https://github.com/SecureAI-Tools/SecureAI-Tools?tab=readme-ov-file#docker-compose-recommended)? The released versions of the docker-compose and env files should be working

**Comment by charlyjna** [comment]
@JayNakrani On my side, I deleted existing containers, volumes, networks, images and created an empty folder to restart from the beginning. I followed the instructions from the link you sent by executing `set-up.sh` and then used docker-compose again.

Unfortunately, I still have the same issue:
`TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]
    at ServerResponse.setHeader (node:_http_outgoing:651:3)
    at _res.setHeader (/app/node_modules/next/dist/server/base-server.js:326:24)
    at NextAuthApiHandler (/app/node_modules/next-auth/next/index.js:43:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextAuth._args$ (/app/node_modules/next-auth/next/index.js:107:14) {
  code: 'ERR_INVALID_CHAR'
}`

**Comment by charlyjna** [comment]
@shuther I am also using the tag latest, and I assume it is the last released one (v0.0.1):

![image](https://github.com/SecureAI-Tools/SecureAI-Tools/assets/117114606/5fffbe26-04f2-42cd-96cf-da663b4fa015)

**Comment by JayNakrani** [comment]
@charlyjna @shuther Sorry for the delay and all the breakages on the main branch. We just released v0.0.2 after fixing all the refactoring issues. Can you please try out the latest version `v0.0.2`? Please make sure to download `docker-compose.yml` and `.env` files from the release page and substitute env vars according to `set-up.sh` script.

Please let me know if you still see any issues in `v0.0.2`. In such a case, I'd love to hop on a quick call and debug this together if you'd like :)

**Comment by paul-hammant** [comment]
I've installed SecureAI-Tools in docker (as the README) but inside a Proxmox LXC container in my infra. I navigate to it via a regular 192.168.0.xxx address, then I see the login form and fill it in, but when I submit the form it seems the POST is hard-coded `localhost` rather than getting the actual domain name from the DOM, or assuming a relative path for the POST without the domain prefex

**Comment by JayNakrani** [comment]
Hi @paul-hammant,

To access from outside the machine, please change the `NEXTAUTH_URL` to `http://192.168.0.xxx` and then it should work. I will try to better document this in README :)

Let me know how it goes.

**Comment by JayNakrani** [comment]
@shuther Ah yes, I think this is because `:latest` doesn't automatically pick up the latest version. Can you try replacing `public.ecr.aws/d8f2p0h3/secure-ai-tools:latest` with `public.ecr.aws/d8f2p0h3/secure-ai-tools:v0.0.2` in `docker-compose.yml` file? There are three services that use this image so make sure to replace in all three places.

**Comment by paul-hammant** [comment]
NEXTAUTH_URL  .. sure.  Seems to login without it being set, it is just the post-redirect-get isn't working, but you can go back to the home page and see that you are now in fact logged in

**Comment by JayNakrani** [comment]
I believe that these issues were happening last week because we were in the middle of a big refactor and so the code on main wasn't stable. This issue should be fixed now with the latest release ([v0.0.3](https://github.com/SecureAI-Tools/SecureAI-Tools/releases/tag/v0.0.3)). Please try the latest release and feel free to ping me if you run into any issues.

Closing this issue for now.
